"""1123232

Revision ID: 2c597c1d908a
Revises: 
Create Date: 2023-08-30 02:05:18.987859

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2c597c1d908a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_map_timestamp', table_name='url_map')
    op.drop_column('url_map', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_url_map_timestamp', 'url_map', ['timestamp'], unique=False)
    # ### end Alembic commands ###
